# PostgreSQL.
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: myapp_development # Change this to your actual dev db name

test:
  <<: *default
  database: myapp_test # Change this to your actual test db name

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  cable: { url: <%= ENV["DATABASE_URL"] %> }